# base image
FROM continuumio/miniconda3:4.7.12

# load in the environment.yml file
ADD ./docker/environment.yaml /

# create the environmnt
RUN conda update -n base conda -y && conda env update --file environment.yaml --prune