# base image
FROM continuumio/miniconda3:4.7.12

# load in the environment.yml file
ADD ./docker/environment.yaml /

# create the environmnt
RUN conda update -n base conda -y && conda env update --file environment.yaml --prune
RUN conda install -c conda-forge nodejs  && \
    jupyter labextension install @jupyterlab/git --no-build && \
    jupyter labextension install @jupyterlab/hub-extension --no-build && \
    jupyter labextension install jupyterlab_tensorboard --no-build && \
    jupyter labextension install @lckr/jupyterlab_variableinspector && \
    jupyter lab build && \
        jupyter lab clean && \
        jlpm cache clean && \
        npm cache clean --force
